### ISSUE TITLE
I can't configure with Ruby

### ISSUE THREAD

**Issue by wellington1993** [anwar3606/Column-Heighlighter#1]
Hi,

I've tried to do this:
```
    // Languages needed to formatted
    "columnHighLighter.languages": [
        "print",
        "Ruby"
    ]
```

What I did wrong?
Thanks...

**Comment by anwar3606** [comment]
@wellington1993 Language id for Ruby is "ruby". Try that, let me know if it works.
Sorry should have mentioned that.
